import { StyleSheet } from "@react-pdf/renderer";

export const shared = StyleSheet.create({
  page:        { fontFamily: "Helvetica", fontSize: 10, padding: 40, color: "#1e293b", backgroundColor: "#fff" },
  header:      { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20, paddingBottom: 16, borderBottomWidth: 2, borderBottomColor: "#059669" },
  logoBlock:   { flexDirection: "column" },
  logo:        { fontSize: 20, fontFamily: "Helvetica-Bold", color: "#059669" },
  logoSub:     { fontSize: 8, color: "#64748b", marginTop: 2 },
  docTitle:    { fontSize: 14, fontFamily: "Helvetica-Bold", color: "#0f172a", textAlign: "right" },
  docNum:      { fontSize: 9, color: "#64748b", textAlign: "right", marginTop: 3 },
  section:     { marginBottom: 14 },
  sectionTitle:{ fontSize: 8, fontFamily: "Helvetica-Bold", color: "#64748b", textTransform: "uppercase", letterSpacing: 1, marginBottom: 5, paddingBottom: 3, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  twoCol:      { flexDirection: "row", gap: 12, marginBottom: 14 },
  col:         { flex: 1, backgroundColor: "#f8fafc", borderRadius: 4, padding: 8, borderWidth: 1, borderColor: "#e2e8f0" },
  colTitle:    { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#059669", marginBottom: 5 },
  colRow:      { flexDirection: "row", marginBottom: 2 },
  colLabel:    { fontSize: 8, color: "#64748b", width: 80 },
  colValue:    { fontSize: 8, color: "#0f172a", flex: 1 },
  table:       { marginBottom: 10 },
  tableHeader: { flexDirection: "row", backgroundColor: "#f1f5f9", paddingVertical: 4, paddingHorizontal: 6, borderRadius: 3 },
  tableRow:    { flexDirection: "row", paddingVertical: 4, paddingHorizontal: 6, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  tableRowAlt: { flexDirection: "row", paddingVertical: 4, paddingHorizontal: 6, backgroundColor: "#f8fafc", borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  thText:      { fontSize: 8, fontFamily: "Helvetica-Bold", color: "#475569" },
  tdText:      { fontSize: 9, color: "#0f172a" },
  totalRow:    { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, paddingHorizontal: 6, backgroundColor: "#ecfdf5", borderRadius: 4, marginTop: 4 },
  totalLabel:  { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#059669" },
  totalValue:  { fontSize: 10, fontFamily: "Helvetica-Bold", color: "#059669", textAlign: "right" },
  bodyText:    { fontSize: 9, color: "#1e293b", lineHeight: 1.6 },
  bold:        { fontFamily: "Helvetica-Bold" },
  sigRow:      { flexDirection: "row", justifyContent: "space-between", marginTop: 30 },
  sigBlock:    { width: "45%" },
  sigLine:     { borderTopWidth: 1, borderTopColor: "#94a3b8", marginTop: 40, paddingTop: 4 },
  sigLabel:    { fontSize: 8, color: "#64748b" },
  footer:      { position: "absolute", bottom: 24, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", fontSize: 8, color: "#94a3b8", borderTopWidth: 1, borderTopColor: "#f1f5f9", paddingTop: 6 },
  watermark:   { fontSize: 8, color: "#64748b", backgroundColor: "#fef9c3", paddingHorizontal: 6, paddingVertical: 3, borderRadius: 3, borderWidth: 1, borderColor: "#fde68a", marginBottom: 12 },
  itemNum:     { width: 20 },
  itemName:    { flex: 3 },
  itemQty:     { width: 30, textAlign: "center" },
  itemUnit:    { width: 35, textAlign: "center" },
  itemPrice:   { width: 60, textAlign: "right" },
  itemTotal:   { width: 65, textAlign: "right" },
});
