import { MetadataRoute } from "next";
import { getPublishedArticles } from "@/lib/blog/articles";

export default function sitemap(): MetadataRoute.Sitemap {
  const articles = getPublishedArticles();

  const articleUrls: MetadataRoute.Sitemap = articles.map((a) => ({
    url: `https://chinabridge.pro/blog/${a.slug}`,
    lastModified: new Date(a.created_at),
    changeFrequency: "monthly",
    priority: 0.6,
  }));

  return [
    { url: "https://chinabridge.pro", lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: "https://chinabridge.pro/ai-calculator", lastModified: new Date(), changeFrequency: "weekly", priority: 0.95 },
    { url: "https://chinabridge.pro/delivery-calculator", lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: "https://chinabridge.pro/fulfilment", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/services", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: "https://chinabridge.pro/services/china-delivery", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/services/1688-buyout", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/services/supplier-search", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/services/cargo-consolidation", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/services/inspection", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/delivery", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/delivery/china-moscow", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/delivery/china-spb", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://chinabridge.pro/delivery/china-khabarovsk", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://chinabridge.pro/delivery/china-blagoveshchensk", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://chinabridge.pro/delivery/china-kazakhstan", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://chinabridge.pro/import-iz-kitaya", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: "https://chinabridge.pro/dostavka-iz-kitaya", lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: "https://chinabridge.pro/rastamozhka", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/postavschiki-kitaya", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/blog", lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: "https://chinabridge.pro/faq", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://chinabridge.pro/contacts", lastModified: new Date(), changeFrequency: "yearly", priority: 0.5 },
    { url: "https://chinabridge.pro/partners", lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: "https://chinabridge.pro/knowledge", lastModified: new Date(), changeFrequency: "weekly", priority: 0.75 },
    { url: "https://chinabridge.pro/product-finder", lastModified: new Date(), changeFrequency: "weekly", priority: 0.85 },
    { url: "https://chinabridge.pro/supplier-finder", lastModified: new Date(), changeFrequency: "weekly", priority: 0.85 },
    { url: "https://chinabridge.pro/elektronika", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/avtozapchasti", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/dom", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/stroy", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/instrument", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/optom", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/odezhda", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/kaspi-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-products-for-wildberries", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-products-for-ozon", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-clothing-from-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-shoes-from-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-furniture-from-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-auto-parts-from-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import-equipment-from-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/b2bchina-alternative", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/supplier-wildberries-china", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/import-china-kazakhstan", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/white-import", lastModified: new Date(), changeFrequency: "monthly", priority: 0.75 },
    { url: "https://chinabridge.pro/wildberries-margin-calculator", lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: "https://chinabridge.pro/import/electronics", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/import/auto-parts", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/import/clothing", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/import/furniture", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/import/equipment", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/import/lighting", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    { url: "https://chinabridge.pro/import/components", lastModified: new Date(), changeFrequency: "monthly", priority: 0.85 },
    ...articleUrls,
  ];
}
