import type { CreateFactInput } from './types';

export const SEED_SOURCES = [
  {
    name:            'ЦБ РФ — XML курсы валют',
    url:             'https://www.cbr.ru/scripts/XML_daily.asp',
    department:      'GENERAL' as const,
    source_type:     'REGULATOR' as const,
    priority:        1,
    active:          true,
    crawl_frequency: 'DAILY' as const,
    notes:           'Автообновление n8n 07:00 UTC. Курсы публикуются ~10:30 МСК.',
  },
  {
    name:            'WB Портал продавца — тарифы',
    url:             'https://seller.wildberries.ru/dynamic-products',
    department:      'WB' as const,
    source_type:     'MARKETPLACE' as const,
    priority:        1,
    active:          true,
    crawl_frequency: 'WEEKLY' as const,
    notes:           'Официальный кабинет. Тарифы меняются по анонсу за 30 дней.',
  },
  {
    name:            'Ozon Портал продавца — тарифы',
    url:             'https://seller.ozon.ru/app/tariffs',
    department:      'OZON' as const,
    source_type:     'MARKETPLACE' as const,
    priority:        1,
    active:          true,
    crawl_frequency: 'WEEKLY' as const,
    notes:           'Официальный кабинет Ozon. Тарифы FBO/FBS.',
  },
  {
    name:            'ЕЭК — Единый таможенный тариф ЕАЭС',
    url:             'https://www.eaeunion.org/files/tnt.html',
    department:      'IMPORT' as const,
    source_type:     'REGULATOR' as const,
    priority:        1,
    active:          true,
    crawl_frequency: 'WEEKLY' as const,
    notes:           'Требует Human Approval при любом изменении ставок.',
  },
  {
    name:            'Kaspi Seller — тарифы',
    url:             'https://kaspi.kz/seller',
    department:      'GENERAL' as const,
    source_type:     'MARKETPLACE' as const,
    priority:        1,
    active:          true,
    crawl_frequency: 'MONTHLY' as const,
    notes:           'Тарифы Kaspi Казахстан. Меняются редко.',
  },
];

export const SEED_FACTS: CreateFactInput[] = [
  // ── Курсы валют ──────────────────────────────────────────────────────────────
  {
    fact_key:          'CNY_RATE',
    department:        'GENERAL',
    category:          'CURRENCY',
    entity:            'CBR',
    metric:            'cny_rub',
    current_value:     '12.4789',
    unit:              'RUB',
    valid_from:        '2026-08-15',
    confidence:        'HIGH',
    impact_level:      'CRITICAL',
    label:             'Курс CNY/RUB (ЦБ РФ)',
    source_url:        'https://www.cbr.ru/scripts/XML_daily.asp',
    requires_approval: false,
    notes:             'Автообновление через n8n 07:00 UTC. Критический — влияет на все расчёты закупки из Китая.',
  },
  {
    fact_key:          'USD_RATE',
    department:        'GENERAL',
    category:          'CURRENCY',
    entity:            'CBR',
    metric:            'usd_rub',
    current_value:     '84.5449',
    unit:              'RUB',
    valid_from:        '2026-08-15',
    confidence:        'HIGH',
    impact_level:      'CRITICAL',
    label:             'Курс USD/RUB (ЦБ РФ)',
    source_url:        'https://www.cbr.ru/scripts/XML_daily.asp',
    requires_approval: false,
    notes:             'Автообновление через n8n 07:00 UTC.',
  },

  // ── Wildberries — комиссии ───────────────────────────────────────────────────
  {
    fact_key:          'WB_GENERAL_COMMISSION',
    department:        'WB',
    category:          'COMMISSION',
    entity:            'WB',
    metric:            'commission_pct',
    current_value:     '23',
    unit:              '%',
    valid_from:        '2026-07-07',
    confidence:        'HIGH',
    impact_level:      'CRITICAL',
    label:             'WB Комиссия — общие категории',
    source_url:        'https://seller.wildberries.ru/dynamic-products',
    requires_approval: true,
    notes:             'Дом, игрушки, спорт. Включает эквайринг 1,5% (РФ). Одежда/обувь: 43,5%.',
  },
  {
    fact_key:          'WB_CLOTHES_COMMISSION',
    department:        'WB',
    category:          'COMMISSION',
    entity:            'WB',
    metric:            'commission_pct',
    current_value:     '43.5',
    unit:              '%',
    valid_from:        '2026-07-07',
    confidence:        'HIGH',
    impact_level:      'HIGH',
    label:             'WB Комиссия — одежда и обувь',
    source_url:        'https://seller.wildberries.ru/dynamic-products',
    requires_approval: true,
    notes:             null,
  },
  {
    fact_key:          'WB_ELECTRONICS_COMMISSION',
    department:        'WB',
    category:          'COMMISSION',
    entity:            'WB',
    metric:            'commission_pct',
    current_value:     '23',
    unit:              '%',
    valid_from:        '2026-07-07',
    confidence:        'MEDIUM',
    impact_level:      'HIGH',
    label:             'WB Комиссия — электроника',
    source_url:        'https://seller.wildberries.ru/dynamic-products',
    requires_approval: true,
    notes:             '23–28% в зависимости от подкатегории. Ноутбуки: 23,5%.',
  },

  // ── Wildberries — логистика ──────────────────────────────────────────────────
  {
    fact_key:          'WB_LOGISTICS_BASE',
    department:        'WB',
    category:          'LOGISTICS',
    entity:            'WB',
    metric:            'logistics_base_rub',
    current_value:     '75',
    unit:              'RUB',
    valid_from:        '2025-09-15',
    confidence:        'MEDIUM',
    impact_level:      'MEDIUM',
    label:             'WB Логистика FBW — базовая ставка (до 0,5кг)',
    source_url:        'https://seller.wildberries.ru/dynamic-products',
    requires_approval: false,
    notes:             'До 0,5кг (~1л). За каждый кг выше 0,5кг: +35₽.',
  },
  {
    fact_key:          'WB_LOGISTICS_PER_KG',
    department:        'WB',
    category:          'LOGISTICS',
    entity:            'WB',
    metric:            'logistics_per_kg_rub',
    current_value:     '35',
    unit:              'RUB/kg',
    valid_from:        '2025-09-15',
    confidence:        'MEDIUM',
    impact_level:      'LOW',
    label:             'WB Логистика FBW — доплата за кг сверх 0,5кг',
    requires_approval: false,
    notes:             null,
  },
  {
    fact_key:          'WB_STORAGE_MONTHLY',
    department:        'WB',
    category:          'STORAGE',
    entity:            'WB',
    metric:            'storage_per_unit_month_rub',
    current_value:     '12',
    unit:              'RUB/ед/мес',
    valid_from:        '2026-01-01',
    confidence:        'MEDIUM',
    impact_level:      'LOW',
    label:             'WB Хранение FBW — за единицу в месяц',
    requires_approval: false,
    notes:             'Приблизительно, при 60-дневной оборачиваемости.',
  },
  {
    fact_key:          'WB_RETURNS_PCT',
    department:        'WB',
    category:          'RETURN',
    entity:            'WB',
    metric:            'returns_pct',
    current_value:     '8',
    unit:              '%',
    valid_from:        '2026-01-01',
    confidence:        'MEDIUM',
    impact_level:      'MEDIUM',
    label:             'WB Средний процент возвратов',
    requires_approval: false,
    notes:             '8% для общих категорий. Одежда/обувь: 20–40%.',
  },

  // ── Ozon — комиссии ─────────────────────────────────────────────────────────
  {
    fact_key:          'OZON_GENERAL_COMMISSION',
    department:        'OZON',
    category:          'COMMISSION',
    entity:            'OZON',
    metric:            'commission_pct',
    current_value:     '18',
    unit:              '%',
    valid_from:        '2026-07-01',
    confidence:        'HIGH',
    impact_level:      'CRITICAL',
    label:             'Ozon Комиссия — общие категории',
    source_url:        'https://seller.ozon.ru/app/tariffs',
    requires_approval: true,
    notes:             'Дом, игрушки. Включает эквайринг.',
  },
  {
    fact_key:          'OZON_CLOTHES_COMMISSION',
    department:        'OZON',
    category:          'COMMISSION',
    entity:            'OZON',
    metric:            'commission_pct',
    current_value:     '22',
    unit:              '%',
    valid_from:        '2026-07-01',
    confidence:        'HIGH',
    impact_level:      'HIGH',
    label:             'Ozon Комиссия — одежда',
    source_url:        'https://seller.ozon.ru/app/tariffs',
    requires_approval: true,
    notes:             null,
  },
  {
    fact_key:          'OZON_SMARTPHONES_COMMISSION',
    department:        'OZON',
    category:          'COMMISSION',
    entity:            'OZON',
    metric:            'commission_pct',
    current_value:     '5',
    unit:              '%',
    valid_from:        '2026-07-01',
    confidence:        'HIGH',
    impact_level:      'HIGH',
    label:             'Ozon Комиссия — смартфоны',
    source_url:        'https://seller.ozon.ru/app/tariffs',
    requires_approval: true,
    notes:             null,
  },
  {
    fact_key:          'OZON_SHOES_COMMISSION',
    department:        'OZON',
    category:          'COMMISSION',
    entity:            'OZON',
    metric:            'commission_pct',
    current_value:     '50',
    unit:              '%',
    valid_from:        '2026-07-01',
    confidence:        'HIGH',
    impact_level:      'HIGH',
    label:             'Ozon Комиссия — обувь',
    source_url:        'https://seller.ozon.ru/app/tariffs',
    requires_approval: true,
    notes:             null,
  },
  {
    fact_key:          'OZON_ELECTRONICS_COMMISSION',
    department:        'OZON',
    category:          'COMMISSION',
    entity:            'OZON',
    metric:            'commission_pct',
    current_value:     '15',
    unit:              '%',
    valid_from:        '2026-07-01',
    confidence:        'MEDIUM',
    impact_level:      'HIGH',
    label:             'Ozon Комиссия — электроника',
    source_url:        'https://seller.ozon.ru/app/tariffs',
    requires_approval: true,
    notes:             null,
  },

  // ── Ozon — логистика/хранение ────────────────────────────────────────────────
  {
    fact_key:          'OZON_LOGISTICS_BASE',
    department:        'OZON',
    category:          'LOGISTICS',
    entity:            'OZON',
    metric:            'logistics_base_rub',
    current_value:     '43',
    unit:              'RUB',
    valid_from:        '2026-07-01',
    confidence:        'MEDIUM',
    impact_level:      'MEDIUM',
    label:             'Ozon Логистика FBO — базовая ставка (до 1л)',
    requires_approval: false,
    notes:             'До 1л (≈0,5кг). Каждый доп. литр: +10₽.',
  },
  {
    fact_key:          'OZON_LOGISTICS_PER_LITER',
    department:        'OZON',
    category:          'LOGISTICS',
    entity:            'OZON',
    metric:            'logistics_per_liter_rub',
    current_value:     '10',
    unit:              'RUB/л',
    valid_from:        '2026-07-01',
    confidence:        'MEDIUM',
    impact_level:      'LOW',
    label:             'Ozon Логистика FBO — доплата за литр',
    requires_approval: false,
    notes:             null,
  },
  {
    fact_key:          'OZON_STORAGE_MONTHLY',
    department:        'OZON',
    category:          'STORAGE',
    entity:            'OZON',
    metric:            'storage_per_unit_month_rub',
    current_value:     '8',
    unit:              'RUB/ед/мес',
    valid_from:        '2026-01-01',
    confidence:        'MEDIUM',
    impact_level:      'LOW',
    label:             'Ozon Хранение FBO — за единицу в месяц',
    requires_approval: false,
    notes:             null,
  },
  {
    fact_key:          'OZON_RETURNS_PCT',
    department:        'OZON',
    category:          'RETURN',
    entity:            'OZON',
    metric:            'returns_pct',
    current_value:     '5',
    unit:              '%',
    valid_from:        '2026-01-01',
    confidence:        'MEDIUM',
    impact_level:      'MEDIUM',
    label:             'Ozon Средний процент возвратов',
    requires_approval: false,
    notes:             null,
  },

  // ── Kaspi ────────────────────────────────────────────────────────────────────
  {
    fact_key:          'KASPI_COMMISSION',
    department:        'GENERAL',
    category:          'COMMISSION',
    entity:            'KASPI',
    metric:            'commission_pct',
    current_value:     '12.6',
    unit:              '%',
    valid_from:        '2026-01-01',
    confidence:        'HIGH',
    impact_level:      'HIGH',
    label:             'Kaspi Комиссия (включая НДС 16% КЗ)',
    requires_approval: true,
    notes:             '10,9% + НДС 16% Казахстана. Рассрочка Fusion: +0,75–5%.',
  },
  {
    fact_key:          'KASPI_LOGISTICS_BASE',
    department:        'GENERAL',
    category:          'LOGISTICS',
    entity:            'KASPI',
    metric:            'logistics_base_rub',
    current_value:     '300',
    unit:              'RUB',
    valid_from:        '2026-01-01',
    confidence:        'LOW',
    impact_level:      'LOW',
    label:             'Kaspi Доставка — базовая ставка',
    requires_approval: false,
    notes:             '1000–2000₸ ≈ 200–400₽. Зависит от зоны доставки.',
  },

  // ── Яндекс Маркет ───────────────────────────────────────────────────────────
  {
    fact_key:          'YANDEX_FBY_COMMISSION',
    department:        'GENERAL',
    category:          'COMMISSION',
    entity:            'YANDEX',
    metric:            'commission_pct',
    current_value:     '12',
    unit:              '%',
    valid_from:        '2026-02-01',
    confidence:        'MEDIUM',
    impact_level:      'HIGH',
    label:             'Яндекс Маркет Комиссия (FBY пакет 2026)',
    requires_approval: true,
    notes:             'Пакет FBY до конца 2026. Last mile: 4,5% (макс. 1000₽).',
  },
  {
    fact_key:          'YANDEX_LAST_MILE_PCT',
    department:        'GENERAL',
    category:          'LOGISTICS',
    entity:            'YANDEX',
    metric:            'last_mile_pct',
    current_value:     '4.5',
    unit:              '%',
    valid_from:        '2026-02-01',
    confidence:        'MEDIUM',
    impact_level:      'LOW',
    label:             'Яндекс Маркет — последняя миля (% от цены, макс. 1000₽)',
    requires_approval: false,
    notes:             null,
  },

  // ── Таможня и налоги ────────────────────────────────────────────────────────
  {
    fact_key:          'CUSTOMS_DUTY_DEFAULT',
    department:        'IMPORT',
    category:          'CUSTOMS',
    entity:            'CUSTOMS',
    metric:            'duty_rate_pct',
    current_value:     '20',
    unit:              '%',
    valid_from:        '2026-01-01',
    confidence:        'MEDIUM',
    impact_level:      'CRITICAL',
    label:             'Таможня — упрощённая ставка (по умолчанию)',
    source_url:        'https://www.eaeunion.org/files/tnt.html',
    requires_approval: true,
    notes:             'ВАЖНО: упрощённый расчёт для калькулятора. Реальные ставки ЕАЭС зависят от кода ТН ВЭД. Используется в calculator.ts и economics/route.ts. AI не генерирует инструкции по обходу таможни.',
  },
  {
    fact_key:          'CUSTOMS_VAT',
    department:        'IMPORT',
    category:          'CUSTOMS',
    entity:            'FNS',
    metric:            'vat_rate_pct',
    current_value:     '20',
    unit:              '%',
    valid_from:        '2019-01-01',
    confidence:        'HIGH',
    impact_level:      'CRITICAL',
    label:             'НДС при ввозе в РФ',
    source_url:        'https://www.nalog.gov.ru',
    requires_approval: true,
    notes:             'НК РФ ст. 164. Стандартная ставка НДС 20%.',
  },

  // ── ChinaBridge внутренние правила ──────────────────────────────────────────
  {
    fact_key:          'DEFAULT_MARKUP_PCT',
    department:        'LOGISTICS',
    category:          'RULE',
    entity:            'CHINABRIDGE',
    metric:            'markup_pct',
    current_value:     '20',
    unit:              '%',
    valid_from:        '2026-01-01',
    confidence:        'HIGH',
    impact_level:      'HIGH',
    label:             'ChinaBridge — наценка по умолчанию',
    requires_approval: false,
    notes:             'lib/cost-engine/pricing-selector.ts DEFAULT_MARKUP. Переопределяется правилами в n8n Data Tables.',
  },
  {
    fact_key:          'TARGET_MARGIN_DEFAULT',
    department:        'LOGISTICS',
    category:          'RULE',
    entity:            'CHINABRIDGE',
    metric:            'target_margin_pct',
    current_value:     '25',
    unit:              '%',
    valid_from:        '2026-01-01',
    confidence:        'HIGH',
    impact_level:      'MEDIUM',
    label:             'ChinaBridge — целевая маржа (для Target Price)',
    requires_approval: false,
    notes:             'lib/economics/calculator.ts computeTargetPrice targetMargin=0.25.',
  },
];
