import type {
  MarketData, Competitor, Opportunity, ProductIdea,
  GrowthAction, Trend, StrategyHealth, StrategyDirectorReport,
} from "./types";

export const MARKETS: MarketData[] = [
  {
    id: "russia",
    name: "Россия",
    size: "18 трлн₽",
    growth: 12,
    competition: "HIGH",
    potential: "HIGH",
    entryDifficulty: "LOW",
    whyEnter: ["Уже присутствуем", "Крупнейший рынок СНГ", "Рост e-commerce"],
    recommendation: "Масштабировать текущие направления, усилить SaaS",
    score: 8,
  },
  {
    id: "kazakhstan",
    name: "Казахстан",
    size: "2.4 трлн₽",
    growth: 28,
    competition: "LOW",
    potential: "VERY_HIGH",
    entryDifficulty: "LOW",
    whyEnter: ["Мало сильных карго", "Рост Kaspi/WB KZ", "Низкий порог входа"],
    recommendation: "Создать отдельный оффер для казахстанских импортёров немедленно",
    score: 9,
  },
  {
    id: "uzbekistan",
    name: "Узбекистан",
    size: "1.1 трлн₽",
    growth: 35,
    competition: "LOW",
    potential: "HIGH",
    entryDifficulty: "MEDIUM",
    whyEnter: ["Быстрый рост", "Нет качественных карго сервисов", "Молодая экономика"],
    recommendation: "Пилот через партнёрский канал, горизонт — 6 месяцев",
    score: 8,
  },
  {
    id: "belarus",
    name: "Беларусь",
    size: "850 млрд₽",
    growth: 15,
    competition: "MEDIUM",
    potential: "MEDIUM",
    entryDifficulty: "MEDIUM",
    whyEnter: ["Транзитный хаб", "Общая логистика с РФ"],
    recommendation: "Партнёрство с местными агентами",
    score: 6,
  },
  {
    id: "kyrgyzstan",
    name: "Кыргызстан",
    size: "220 млрд₽",
    growth: 22,
    competition: "LOW",
    potential: "MEDIUM",
    entryDifficulty: "LOW",
    whyEnter: ["Низкая конкуренция", "Китайский транзит"],
    recommendation: "Включить в пакет «Центральная Азия»",
    score: 5,
  },
  {
    id: "uae",
    name: "ОАЭ",
    size: "5.2 трлн₽",
    growth: 18,
    competition: "HIGH",
    potential: "HIGH",
    entryDifficulty: "HIGH",
    whyEnter: ["Хаб для реэкспорта", "Высокая маржа", "Платёжеспособный рынок"],
    recommendation: "Долгосрочная цель — 2027, сейчас наблюдение",
    score: 7,
  },
];

export const COMPETITORS: Competitor[] = [
  {
    id: "c1",
    name: "CDEK Cargo",
    category: "cargo",
    strengths: ["Бренд", "Широкая сеть", "Маркетинг"],
    weaknesses: ["Нет AI", "Нет CRM для импортёров", "Высокие цены"],
    threat: "MEDIUM",
    opportunity: "Предложить AI-платформу как White Label партнёрам CDEK",
    marketShare: "~18%",
  },
  {
    id: "c2",
    name: "ВЭД-Лайн",
    category: "logistics",
    strengths: ["Опыт ВЭД", "Казахстан", "Юридический отдел"],
    weaknesses: ["Устаревший сайт", "Нет цифрового продукта", "Ручные процессы"],
    threat: "LOW",
    opportunity: "Переманить клиентов через digital-первый подход и AI-калькулятор",
  },
  {
    id: "c3",
    name: "ImportKit (SaaS)",
    category: "saas",
    strengths: ["Технологии", "Удобный UI", "Интеграции"],
    weaknesses: ["Нет логистики", "Нет команды в Китае", "Нет русского рынка"],
    threat: "LOW",
    opportunity: "ChinaBridge = full-stack: SaaS + реальная карго + команда в Китае",
  },
  {
    id: "c4",
    name: "Alibaba B2B",
    category: "marketplace",
    strengths: ["Масштаб", "Глобальный бренд", "Ценообразование"],
    weaknesses: ["Нет русскоязычного сервиса", "Нет таможни", "Нет доставки в СНГ"],
    threat: "MEDIUM",
    opportunity: "Стать официальным русскоязычным агентом Alibaba для рынка СНГ",
    marketShare: "~35%",
  },
];

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "o1",
    title: "White Label SaaS для карго компаний",
    category: "product",
    potential: "VERY_HIGH",
    why: "Сотни карго компаний в СНГ без цифровых инструментов — готовый рынок",
    score: 9,
    timeToMarket: "3 месяца",
    revenueEstimate: "500К₽/мес при 10 клиентах",
    effort: "MEDIUM",
  },
  {
    id: "o2",
    title: "Казахстанское направление",
    category: "market",
    potential: "VERY_HIGH",
    why: "Рост рынка 28%/год, конкурентов мало, вход практически без барьеров",
    score: 9,
    timeToMarket: "1 месяц",
    revenueEstimate: "800К₽/мес потенциал",
    effort: "LOW",
  },
  {
    id: "o3",
    title: "AI Import Assistant (B2B SaaS)",
    category: "technology",
    potential: "HIGH",
    why: "Импортёры тратят часы на расчёты, подбор поставщиков, документы — нет решений",
    score: 8,
    timeToMarket: "2 месяца",
    revenueEstimate: "35К₽/мес/клиент",
    effort: "HIGH",
  },
  {
    id: "o4",
    title: "Импорт оборудования и автозапчастей",
    category: "market",
    potential: "HIGH",
    why: "Высокая маржа, повторные B2B заказы, дефицит после санкций",
    score: 7,
    timeToMarket: "2 месяца",
    revenueEstimate: "1.2 млн₽/мес потенциал",
    effort: "MEDIUM",
  },
  {
    id: "o5",
    title: "YouTube Shorts контент-маркетинг",
    category: "market",
    potential: "HIGH",
    why: "Органический трафик = 0₽ CAC, лиды приходят через образовательный контент",
    score: 8,
    timeToMarket: "сейчас",
    revenueEstimate: "Снижение CAC на 40%",
    effort: "LOW",
  },
  {
    id: "o6",
    title: "Партнёрская программа для агентов",
    category: "partnership",
    potential: "HIGH",
    why: "Реферальный рост без рекламных затрат, масштабируется до сотен агентов",
    score: 7,
    timeToMarket: "1 месяц",
    revenueEstimate: "+30% к выручке",
    effort: "LOW",
  },
];

export const PRODUCT_IDEAS: ProductIdea[] = [
  {
    id: "p1",
    title: "Автоматический расчёт таможенных пошлин",
    priority: "HIGH",
    source: "clients",
    description: "Импортёр вводит товар и сумму — система считает ТН ВЭД и пошлину автоматически",
    impact: "Снижение ошибок на 80%, экономия 2 часа/сделка",
    effort: "MEDIUM",
    revenueModel: "Включить в Pro план",
  },
  {
    id: "p2",
    title: "AI Подбор поставщика на 1688",
    priority: "HIGH",
    source: "market",
    description: "Клиент описывает товар, AI ищет и ранжирует поставщиков по рейтингу и цене",
    impact: "Конкурентное преимущество — нет аналогов на рынке СНГ",
    effort: "HIGH",
    revenueModel: "Premium feature",
  },
  {
    id: "p3",
    title: "CRM White Label для карго партнёров",
    priority: "HIGH",
    source: "market",
    description: "ChinaBridge CRM перепродаётся как White Label малым карго компаниям",
    impact: "Новый B2B SaaS поток, минимум 10 клиентов в первый год",
    effort: "MEDIUM",
    revenueModel: "SaaS 35К₽/мес",
  },
  {
    id: "p4",
    title: "Мобильный трекинг заказа",
    priority: "HIGH",
    source: "clients",
    description: "Клиент видит статус груза в реальном времени в мобильном приложении",
    impact: "NPS +20 пунктов, снижение запросов в поддержку на 50%",
    effort: "HIGH",
  },
  {
    id: "p5",
    title: "Интеграция с Wildberries / Ozon API",
    priority: "MEDIUM",
    source: "clients",
    description: "Автоматическая передача данных о заказе в карточку маркетплейса",
    impact: "Ключевая ценность для МП-продавцов, ускоряет онбординг",
    effort: "MEDIUM",
  },
  {
    id: "p6",
    title: "Документооборот AI (автогенерация CMR, invoice)",
    priority: "MEDIUM",
    source: "team",
    description: "AI генерирует транспортные документы по данным заказа за 30 секунд",
    impact: "Сокращение ручной работы на 3 часа/сделка",
    effort: "LOW",
    revenueModel: "Включить в Business план",
  },
];

export const GROWTH_ACTIONS: GrowthAction[] = [
  {
    id: "g1",
    timeframe: "30d",
    title: "Запустить оффер для Казахстана",
    description: "Отдельная лендинг-страница + таргет на казахстанских импортёров",
    owner: "Marketing AI",
    kpi: "5 первых клиентов из KZ",
    priority: "HIGH",
  },
  {
    id: "g2",
    timeframe: "30d",
    title: "White Label SaaS: первые 3 переговоры",
    description: "Найти 3 карго компании для пилота White Label платформы",
    owner: "Sales AI",
    kpi: "3 подписанных договора / NDA",
    priority: "HIGH",
  },
  {
    id: "g3",
    timeframe: "60d",
    title: "Запустить партнёрскую программу",
    description: "Реферальная программа: агент получает 10% от первой сделки клиента",
    owner: "Marketing AI",
    kpi: "10 активных партнёров",
    priority: "HIGH",
  },
  {
    id: "g4",
    timeframe: "60d",
    title: "Таможенный калькулятор v1",
    description: "Реализовать базовый расчёт пошлин в клиентском кабинете",
    owner: "Product AI",
    kpi: "Протестирован 20 клиентами, NPS > 8",
    priority: "HIGH",
  },
  {
    id: "g5",
    timeframe: "90d",
    title: "SaaS Beta: 10 платящих карго компаний",
    description: "Продать White Label SaaS 10 карго компаниям по 35К₽/мес",
    owner: "Sales AI",
    kpi: "MRR +350К₽",
    priority: "HIGH",
  },
  {
    id: "g6",
    timeframe: "90d",
    title: "YouTube: 10 Shorts + 2 длинных видео",
    description: "Контент-маркетинг для снижения CAC через органический трафик",
    owner: "Content AI",
    kpi: "5000+ суммарных просмотров",
    priority: "MEDIUM",
  },
];

export const TRENDS: Trend[] = [
  {
    id: "t1",
    category: "ai",
    title: "AI-агенты для B2B закупок",
    description: "Компании внедряют AI для поиска поставщиков и автоматизации переговоров",
    opportunity: "ChinaBridge = первый AI-агент импорта из Китая для рынка СНГ",
    priority: "HIGH",
    impact: "HIGH",
  },
  {
    id: "t2",
    category: "marketplace",
    title: "Рост казахстанских маркетплейсов",
    description: "Kaspi, Wildberries KZ растут 35%/год, спрос на китайские товары рекордный",
    opportunity: "Специализированный сервис для казахстанских МП-продавцов-импортёров",
    priority: "HIGH",
    impact: "HIGH",
  },
  {
    id: "t3",
    category: "ai",
    title: "Видеоконтент как главный B2B-канал",
    description: "YouTube Shorts и ВК Клипы становятся ключевыми B2B-каналами привлечения",
    opportunity: "Уже производим Shorts — ускорить до 3 видео в неделю",
    priority: "HIGH",
    impact: "HIGH",
  },
  {
    id: "t4",
    category: "legal",
    title: "Новые требования к таможенной документации",
    description: "Ужесточение требований к ВЭД документам с 2026 года",
    opportunity: "Платный сервис проверки и автогенерации документов — уже в ТЗ",
    priority: "HIGH",
    impact: "HIGH",
  },
  {
    id: "t5",
    category: "trade",
    title: "Параллельный импорт — легализация",
    description: "Государства СНГ упрощают правила параллельного импорта",
    opportunity: "Консалтинг по легальному параллельному импорту + специальный тариф",
    priority: "MEDIUM",
    impact: "MEDIUM",
  },
  {
    id: "t6",
    category: "logistics",
    title: "Новые ж/д маршруты Китай-СНГ",
    description: "Открываются новые ж/д коридоры, сокращается время доставки на 40%",
    opportunity: "Ж/д как альтернатива авиа для средних грузов — снижение стоимости",
    priority: "MEDIUM",
    impact: "MEDIUM",
  },
];

function buildHealth(): StrategyHealth {
  const marketScore      = Math.round(MARKETS.reduce((s, m) => s + m.score, 0) / MARKETS.length * 10);
  const innovationScore  = Math.round(PRODUCT_IDEAS.filter(p => p.priority === "HIGH").length / PRODUCT_IDEAS.length * 100);
  const competitiveScore = Math.round((COMPETITORS.filter(c => c.threat !== "HIGH").length / COMPETITORS.length) * 100);
  const score = Math.round((marketScore * 0.35 + innovationScore * 0.35 + competitiveScore * 0.30));

  return {
    score,
    status: score >= 70 ? "GOOD" : score >= 45 ? "WARNING" : "CRITICAL",
    marketScore,
    innovationScore,
    competitiveScore,
    opportunitiesCount: OPPORTUNITIES.length,
    risks: [
      "Конкуренты могут скопировать калькулятор",
      "Медленный рост продаж без партнёрской программы",
      "Отсутствие мобильного приложения — слабость vs крупных игроков",
    ],
    strengths: [
      "Единственный full-stack игрок: карго + SaaS + AI + команда в Китае",
      "SaaS направление: маржа 85%, LTV/CAC > 20x",
      "Казахстан: рынок открыт, конкурентов почти нет",
    ],
  };
}

export function fetchStrategyData() {
  const health = buildHealth();
  return {
    health,
    markets:      MARKETS,
    competitors:  COMPETITORS,
    opportunities: OPPORTUNITIES,
    productIdeas: PRODUCT_IDEAS,
    growthActions: GROWTH_ACTIONS,
    trends:       TRENDS,
  };
}

export type StrategyData = ReturnType<typeof fetchStrategyData>;
